DROP TABLE `achievements`;--> statement-breakpoint
DROP TABLE `character_achievement_unlocks`;--> statement-breakpoint
DROP TABLE `leaderboard_entries`;--> statement-breakpoint
DROP TABLE `leaderboards`;--> statement-breakpoint
DROP TABLE `abilities`;--> statement-breakpoint
DROP TABLE `character_abilities`;--> statement-breakpoint
DROP TABLE `character_modifiers`;--> statement-breakpoint
DROP TABLE `character_skills`;--> statement-breakpoint
DROP TABLE `characters`;--> statement-breakpoint
DROP TABLE `modifiers`;--> statement-breakpoint
DROP TABLE `character_stats`;--> statement-breakpoint
DROP TABLE `skills`;--> statement-breakpoint
DROP TABLE `armor_details`;--> statement-breakpoint
DROP TABLE `character_equipment`;--> statement-breakpoint
DROP TABLE `character_inventory`;--> statement-breakpoint
DROP TABLE `equipment_slots`;--> statement-breakpoint
DROP TABLE `item_modifiers`;--> statement-breakpoint
DROP TABLE `items`;--> statement-breakpoint
DROP TABLE `potion_details`;--> statement-breakpoint
DROP TABLE `weapon_details`;--> statement-breakpoint
DROP TABLE `answers`;--> statement-breakpoint
DROP TABLE `languages`;--> statement-breakpoint
DROP TABLE `lesson_sections`;--> statement-breakpoint
DROP TABLE `lessons`;--> statement-breakpoint
DROP TABLE `questions`;--> statement-breakpoint
DROP TABLE `quizzes`;--> statement-breakpoint
DROP TABLE `translations`;--> statement-breakpoint
DROP TABLE `ui_labels`;--> statement-breakpoint
DROP TABLE `audio_feedback`;--> statement-breakpoint
DROP TABLE `audio_uploads`;--> statement-breakpoint
DROP TABLE `media_assets`;--> statement-breakpoint
DROP TABLE `playable_class_passives`;--> statement-breakpoint
DROP TABLE `playable_class_stat_bonuses`;--> statement-breakpoint
DROP TABLE `playable_class_tag_links`;--> statement-breakpoint
DROP TABLE `playable_classes`;--> statement-breakpoint
DROP TABLE `playable_species`;--> statement-breakpoint
DROP TABLE `playable_species_abilities`;--> statement-breakpoint
DROP TABLE `playable_species_lore`;--> statement-breakpoint
DROP TABLE `playable_species_stat_bonuses`;--> statement-breakpoint
DROP TABLE `playable_species_tags`;--> statement-breakpoint
DROP TABLE `playable_tag_categories`;--> statement-breakpoint
DROP TABLE `playable_tag_category_links`;--> statement-breakpoint
DROP TABLE `playable_tags`;--> statement-breakpoint
DROP TABLE `campaigns`;--> statement-breakpoint
DROP TABLE `character_quest_progress`;--> statement-breakpoint
DROP TABLE `quest_objective_links`;--> statement-breakpoint
DROP TABLE `quest_objectives`;--> statement-breakpoint
DROP TABLE `quest_rewards`;--> statement-breakpoint
DROP TABLE `quests`;--> statement-breakpoint
DROP TABLE `class_enrollments`;--> statement-breakpoint
DROP TABLE `classes`;--> statement-breakpoint
DROP TABLE `teacher_profiles`;--> statement-breakpoint
DROP TABLE `friends`;--> statement-breakpoint
DROP TABLE `messages`;--> statement-breakpoint
DROP TABLE `notifications`;--> statement-breakpoint
DROP TABLE `parties`;--> statement-breakpoint
DROP TABLE `party_members`;--> statement-breakpoint
DROP TABLE `admin_logs`;--> statement-breakpoint
DROP TABLE `bans`;--> statement-breakpoint
DROP TABLE `settings`;--> statement-breakpoint
DROP TABLE `support_tickets`;--> statement-breakpoint
DROP TABLE `playable_stats`;