/**
 * =========================================================
 * RFL SEED DATA
 * =========================================================
 *
 * Domain: Canon Bridge
 * Subdomain: Reference Tables — World Structure Systems
 *
 * Purpose:
 * Defines canonical seed data for world-structure-related
 * reference tables.
 *
 * Notes:
 * - These objects use application-side property names
 *   (displayName, sortOrder, etc.) rather than raw SQL names.
 * - IDs and timestamps are intentionally omitted and handled
 *   by the schema defaults / seed runner unless explicitly
 *   required by canonical hierarchy references.
 * - Reference tables define controlled vocabularies used
 *   throughout the Canon Bridge and Portal layers.
 *
 * =========================================================
 */

export const locationTypesSeed = [
  {
    id: 'loc_type_world',
    name: 'world',
    slug: 'world',
    displayName: 'World',
    description: 'The highest-level world container.',
    parentLocationTypeId: null,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'loc_type_region',
    name: 'region',
    slug: 'region',
    displayName: 'Region',
    description: 'A broad geographic or political area.',
    parentLocationTypeId: null,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'loc_type_biome',
    name: 'biome',
    slug: 'biome',
    displayName: 'Biome',
    description: 'A large-scale environmental zone defined by climate and ecology.',
    parentLocationTypeId: null,
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 'loc_type_settlement',
    name: 'settlement',
    slug: 'settlement',
    displayName: 'Settlement',
    description: 'An inhabited location where people live.',
    parentLocationTypeId: null,
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 'loc_type_structure',
    name: 'structure',
    slug: 'structure',
    displayName: 'Structure',
    description: 'A constructed physical location.',
    parentLocationTypeId: null,
    isActive: true,
    sortOrder: 5,
  },
  {
    id: 'loc_type_site',
    name: 'site',
    slug: 'site',
    displayName: 'Site',
    description: 'A notable or unique point of interest.',
    parentLocationTypeId: null,
    isActive: true,
    sortOrder: 6,
  },
  {
    id: 'loc_type_continent',
    name: 'continent',
    slug: 'continent',
    displayName: 'Continent',
    description: 'A major landmass within the world.',
    parentLocationTypeId: 'loc_type_world',
    isActive: true,
    sortOrder: 10,
  },
  {
    id: 'loc_type_realm',
    name: 'realm',
    slug: 'realm',
    displayName: 'Realm',
    description: 'A large, often culturally or magically unified domain.',
    parentLocationTypeId: 'loc_type_world',
    isActive: true,
    sortOrder: 11,
  },
  {
    id: 'loc_type_kingdom',
    name: 'kingdom',
    slug: 'kingdom',
    displayName: 'Kingdom',
    description: 'A ruled political region.',
    parentLocationTypeId: 'loc_type_region',
    isActive: true,
    sortOrder: 20,
  },
  {
    id: 'loc_type_province',
    name: 'province',
    slug: 'province',
    displayName: 'Province',
    description: 'A subdivision of a larger political region.',
    parentLocationTypeId: 'loc_type_region',
    isActive: true,
    sortOrder: 21,
  },
  {
    id: 'loc_type_territory',
    name: 'territory',
    slug: 'territory',
    displayName: 'Territory',
    description: 'A loosely defined or controlled region.',
    parentLocationTypeId: 'loc_type_region',
    isActive: true,
    sortOrder: 22,
  },
  {
    id: 'loc_type_forest',
    name: 'forest',
    slug: 'forest',
    displayName: 'Forest',
    description: 'A dense region dominated by trees and vegetation.',
    parentLocationTypeId: 'loc_type_biome',
    isActive: true,
    sortOrder: 30,
  },
  {
    id: 'loc_type_desert',
    name: 'desert',
    slug: 'desert',
    displayName: 'Desert',
    description: 'A dry, arid region with minimal precipitation.',
    parentLocationTypeId: 'loc_type_biome',
    isActive: true,
    sortOrder: 31,
  },
  {
    id: 'loc_type_mountain_range',
    name: 'mountain_range',
    slug: 'mountain-range',
    displayName: 'Mountain Range',
    description: 'A connected series of mountains.',
    parentLocationTypeId: 'loc_type_biome',
    isActive: true,
    sortOrder: 32,
  },
  {
    id: 'loc_type_swamp',
    name: 'swamp',
    slug: 'swamp',
    displayName: 'Swamp',
    description: 'A wetland region with saturated ground and vegetation.',
    parentLocationTypeId: 'loc_type_biome',
    isActive: true,
    sortOrder: 33,
  },
  {
    id: 'loc_type_plains',
    name: 'plains',
    slug: 'plains',
    displayName: 'Plains',
    description: 'A flat, open region with minimal elevation change.',
    parentLocationTypeId: 'loc_type_biome',
    isActive: true,
    sortOrder: 34,
  },
  {
    id: 'loc_type_tundra',
    name: 'tundra',
    slug: 'tundra',
    displayName: 'Tundra',
    description: 'A cold, treeless region with frozen ground.',
    parentLocationTypeId: 'loc_type_biome',
    isActive: true,
    sortOrder: 35,
  },
  {
    id: 'loc_type_city',
    name: 'city',
    slug: 'city',
    displayName: 'City',
    description: 'A large, densely populated settlement.',
    parentLocationTypeId: 'loc_type_settlement',
    isActive: true,
    sortOrder: 40,
  },
  {
    id: 'loc_type_town',
    name: 'town',
    slug: 'town',
    displayName: 'Town',
    description: 'A mid-sized settlement.',
    parentLocationTypeId: 'loc_type_settlement',
    isActive: true,
    sortOrder: 41,
  },
  {
    id: 'loc_type_village',
    name: 'village',
    slug: 'village',
    displayName: 'Village',
    description: 'A small settlement.',
    parentLocationTypeId: 'loc_type_settlement',
    isActive: true,
    sortOrder: 42,
  },
  {
    id: 'loc_type_outpost',
    name: 'outpost',
    slug: 'outpost',
    displayName: 'Outpost',
    description: 'A small, often remote settlement or station.',
    parentLocationTypeId: 'loc_type_settlement',
    isActive: true,
    sortOrder: 43,
  },
  {
    id: 'loc_type_fortress',
    name: 'fortress',
    slug: 'fortress',
    displayName: 'Fortress',
    description: 'A heavily fortified structure.',
    parentLocationTypeId: 'loc_type_structure',
    isActive: true,
    sortOrder: 50,
  },
  {
    id: 'loc_type_temple',
    name: 'temple',
    slug: 'temple',
    displayName: 'Temple',
    description: 'A place of worship or spiritual significance.',
    parentLocationTypeId: 'loc_type_structure',
    isActive: true,
    sortOrder: 51,
  },
  {
    id: 'loc_type_ruin',
    name: 'ruin',
    slug: 'ruin',
    displayName: 'Ruin',
    description: 'The remains of a once-functional structure.',
    parentLocationTypeId: 'loc_type_structure',
    isActive: true,
    sortOrder: 52,
  },
  {
    id: 'loc_type_dungeon',
    name: 'dungeon',
    slug: 'dungeon',
    displayName: 'Dungeon',
    description: 'A dangerous, enclosed area often used for encounters.',
    parentLocationTypeId: 'loc_type_structure',
    isActive: true,
    sortOrder: 53,
  },
  {
    id: 'loc_type_tower',
    name: 'tower',
    slug: 'tower',
    displayName: 'Tower',
    description: 'A tall, vertical structure.',
    parentLocationTypeId: 'loc_type_structure',
    isActive: true,
    sortOrder: 54,
  },
  {
    id: 'loc_type_shrine',
    name: 'shrine',
    slug: 'shrine',
    displayName: 'Shrine',
    description: 'A small sacred or ritual site.',
    parentLocationTypeId: 'loc_type_site',
    isActive: true,
    sortOrder: 60,
  },
  {
    id: 'loc_type_landmark',
    name: 'landmark',
    slug: 'landmark',
    displayName: 'Landmark',
    description: 'A notable or recognizable feature in the world.',
    parentLocationTypeId: 'loc_type_site',
    isActive: true,
    sortOrder: 61,
  },
  {
    id: 'loc_type_fissure',
    name: 'fissure',
    slug: 'fissure',
    displayName: 'Fissure',
    description: 'A deep crack or rupture in the ground.',
    parentLocationTypeId: 'loc_type_site',
    isActive: true,
    sortOrder: 62,
  },
  {
    id: 'loc_type_camp',
    name: 'camp',
    slug: 'camp',
    displayName: 'Camp',
    description: 'A temporary or semi-permanent place of rest or activity.',
    parentLocationTypeId: 'loc_type_site',
    isActive: true,
    sortOrder: 63,
  },
  {
    id: 'loc_type_district',
    name: 'district',
    slug: 'district',
    displayName: 'District',
    description: 'A defined subdivision within a larger settlement, typically organized around a shared function, identity, or geographic boundary.',
    parentLocationTypeId: 'loc_type_settlement',
    isActive: true,
    sortOrder: 64,
  },
];

export const locationTagsSeed = [
  {
    id: 'loc_tag_coastal',
    name: 'coastal',
    slug: 'coastal',
    displayName: 'Coastal',
    description: 'Located along or near a coastline.',
    tagCategory: 'geography',
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'loc_tag_inland',
    name: 'inland',
    slug: 'inland',
    displayName: 'Inland',
    description: 'Located away from coastal regions.',
    tagCategory: 'geography',
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'loc_tag_mountainous',
    name: 'mountainous',
    slug: 'mountainous',
    displayName: 'Mountainous',
    description: 'Characterized by rugged or elevated terrain.',
    tagCategory: 'geography',
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 'loc_tag_riverine',
    name: 'riverine',
    slug: 'riverine',
    displayName: 'Riverine',
    description: 'Situated along or influenced by a river.',
    tagCategory: 'geography',
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 'loc_tag_remote',
    name: 'remote',
    slug: 'remote',
    displayName: 'Remote',
    description: 'Isolated or distant from major population centers.',
    tagCategory: 'geography',
    isActive: true,
    sortOrder: 5,
  },
  {
    id: 'loc_tag_fertile',
    name: 'fertile',
    slug: 'fertile',
    displayName: 'Fertile',
    description: 'Rich in natural resources suitable for growth or agriculture.',
    tagCategory: 'environmental',
    isActive: true,
    sortOrder: 10,
  },
  {
    id: 'loc_tag_arid',
    name: 'arid',
    slug: 'arid',
    displayName: 'Arid',
    description: 'Extremely dry with little precipitation.',
    tagCategory: 'environmental',
    isActive: true,
    sortOrder: 11,
  },
  {
    id: 'loc_tag_frozen',
    name: 'frozen',
    slug: 'frozen',
    displayName: 'Frozen',
    description: 'Dominated by cold temperatures and ice.',
    tagCategory: 'environmental',
    isActive: true,
    sortOrder: 12,
  },
  {
    id: 'loc_tag_lush',
    name: 'lush',
    slug: 'lush',
    displayName: 'Lush',
    description: 'Dense and thriving with vegetation.',
    tagCategory: 'environmental',
    isActive: true,
    sortOrder: 13,
  },
  {
    id: 'loc_tag_hazardous',
    name: 'hazardous',
    slug: 'hazardous',
    displayName: 'Hazardous',
    description: 'Presents environmental or natural dangers.',
    tagCategory: 'environmental',
    isActive: true,
    sortOrder: 14,
  },
  {
    id: 'loc_tag_sacred',
    name: 'sacred',
    slug: 'sacred',
    displayName: 'Sacred',
    description: 'Holds religious or spiritual significance.',
    tagCategory: 'cultural',
    isActive: true,
    sortOrder: 20,
  },
  {
    id: 'loc_tag_ruined',
    name: 'ruined',
    slug: 'ruined',
    displayName: 'Ruined',
    description: 'In a state of decay or destruction.',
    tagCategory: 'cultural',
    isActive: true,
    sortOrder: 21,
  },
  {
    id: 'loc_tag_ancient',
    name: 'ancient',
    slug: 'ancient',
    displayName: 'Ancient',
    description: 'Originating from a distant past.',
    tagCategory: 'cultural',
    isActive: true,
    sortOrder: 22,
  },
  {
    id: 'loc_tag_mystical',
    name: 'mystical',
    slug: 'mystical',
    displayName: 'Mystical',
    description: 'Associated with magical or supernatural forces.',
    tagCategory: 'cultural',
    isActive: true,
    sortOrder: 23,
  },
  {
    id: 'loc_tag_populated',
    name: 'populated',
    slug: 'populated',
    displayName: 'Populated',
    description: 'Actively inhabited by people or beings.',
    tagCategory: 'cultural',
    isActive: true,
    sortOrder: 24,
  },
  {
    id: 'loc_tag_capital',
    name: 'capital',
    slug: 'capital',
    displayName: 'Capital',
    description: 'Serves as the central seat of governance.',
    tagCategory: 'political',
    isActive: true,
    sortOrder: 30,
  },
  {
    id: 'loc_tag_contested',
    name: 'contested',
    slug: 'contested',
    displayName: 'Contested',
    description: 'Disputed or fought over by multiple groups.',
    tagCategory: 'political',
    isActive: true,
    sortOrder: 31,
  },
  {
    id: 'loc_tag_stable',
    name: 'stable',
    slug: 'stable',
    displayName: 'Stable',
    description: 'Politically or socially stable.',
    tagCategory: 'political',
    isActive: true,
    sortOrder: 32,
  },
  {
    id: 'loc_tag_frontier',
    name: 'frontier',
    slug: 'frontier',
    displayName: 'Frontier',
    description: 'Located at the edge of settled or controlled regions.',
    tagCategory: 'political',
    isActive: true,
    sortOrder: 33,
  },
  {
    id: 'loc_tag_fortified',
    name: 'fortified',
    slug: 'fortified',
    displayName: 'Fortified',
    description: 'Defended with walls, structures, or military presence.',
    tagCategory: 'strategic',
    isActive: true,
    sortOrder: 40,
  },
  {
    id: 'loc_tag_trade_hub',
    name: 'trade_hub',
    slug: 'trade-hub',
    displayName: 'Trade Hub',
    description: 'A center of commerce and exchange.',
    tagCategory: 'strategic',
    isActive: true,
    sortOrder: 41,
  },
  {
    id: 'loc_tag_resource_rich',
    name: 'resource_rich',
    slug: 'resource-rich',
    displayName: 'Resource Rich',
    description: 'Contains valuable natural resources.',
    tagCategory: 'strategic',
    isActive: true,
    sortOrder: 42,
  },
  {
    id: 'loc_tag_hidden',
    name: 'hidden',
    slug: 'hidden',
    displayName: 'Hidden',
    description: 'Concealed or difficult to discover.',
    tagCategory: 'strategic',
    isActive: true,
    sortOrder: 43,
  },
  {
    id: 'loc_tag_chokepoint',
    name: 'chokepoint',
    slug: 'chokepoint',
    displayName: 'Chokepoint',
    description: 'A strategically narrow or critical passage.',
    tagCategory: 'strategic',
    isActive: true,
    sortOrder: 44,
  },
];